---
kind: pipeline
name: build-images

steps:
- name: build-ppc-image-latest
  image: plugins/docker
  settings:
    repo: walkero/docker4amigavbcc
    tags:
      - "latest-ppc"
      - ppc-${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
    cache_from:
      - ppc-${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
    dockerfile: ppc/Dockerfile
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  when:
    event:
      exclude:
        - tag
- name: build-m68k-image-latest
  image: plugins/docker
  settings:
    repo: walkero/docker4amigavbcc
    tags:
      - "latest-m68k"
      - m68k-${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
    cache_from:
      - m68k-${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
    dockerfile: m68k/Dockerfile
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  when:
    event:
      exclude:
        - tag
- name: Fetch full git repo
  image: alpine/git
  commands:
    - git fetch --all
  when:
    event:
      - tag
- name: build-image-from-tag
  image: plugins/docker
  settings:
    repo: walkero/docker4amigavbcc
    tags:
      - testtag
    # cache_from:
    #   - ${DRONE_REPO,,}:master-${DRONE_COMMIT_SHA:0:8}
    dockerfile: ppc/Dockerfile
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  when:
    event:
      - tag