---
kind: pipeline
name: build-images

steps:
- name: build-ppc-image-master
  image: plugins/docker
  settings:
    repo: walkero/docker4amigavbcc
    tags:
      - "latest-ppc"
      - "latest-ppc-${DRONE_COMMIT_SHA:0:8}"
    cache_from:
      - ${DRONE_REPO,,}:${DRONE_SOURCE_BRANCH/\//-}
    dockerfile: ppc/Dockerfile
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  when:
    event:
      exclude:
        - tag