---
kind: pipeline
name: build-image

steps:
- name: build-ppc-image
  image: plugins/docker
  settings:
    repo: walkero/docker4amigavbcc # ${DRONE_REPO,,}
    tags:
      - ${DRONE_TAG/\//-}
      - latest-${DRONE_TAG:4:4}
    cache_from:
      - ${DRONE_REPO,,}:master-${DRONE_COMMIT_SHA:0:8}
    dockerfile: ${DRONE_TAG:4:4}/Dockerfile
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  when:
    event:
      - tag
