---
kind: pipeline
name: build-images

steps:
- name: Fetch full git repo
  image: alpine/git
  commands:
    - git fetch --all
- name: build-ppc-image-latest
  image: plugins/docker
  settings:
    repo: walkero/docker4amigavbcc
    tags:
      - "latest-ppc"
    cache_from:
      - ${DRONE_REPO,,}:${DRONE_SOURCE_BRANCH/\//-}
    dockerfile: ppc/Dockerfile
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  when:
    event:
      exclude:
        - tag
- name: build-m68k-image-latest
  image: plugins/docker
  settings:
    repo: walkero/docker4amigavbcc
    tags:
      - "latest-m68k"
    cache_from:
      - ${DRONE_REPO,,}:${DRONE_SOURCE_BRANCH/\//-}
    dockerfile: m68k/Dockerfile
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  when:
    event:
      exclude:
        - tag
# - name: build-${DRONE_TAG:4:4}-image-tag
#   image: plugins/docker
#   settings:
#     repo: walkero/docker4amigavbcc
#     tags:
#       - ${DRONE_TAG/\//-}
#     cache_from:
#       - ${DRONE_REPO,,}:master-${DRONE_COMMIT_SHA:0:8}
#     dockerfile: ${DRONE_TAG:4:4}/Dockerfile
#     username:
#       from_secret: DOCKERHUB_USERNAME
#     password:
#       from_secret: DOCKERHUB_PASSWORD
#   when:
#     event:
#       - tag